#!/usr/bin/env python3
"""
Email Configuration Setup Script
This script helps you configure the email service for MatrixLead AI
"""

import os
import sys
from pathlib import Path


def print_header():
    print("=" * 60)
    print("  MatrixLead AI - Email Service Configuration")
    print("=" * 60)
    print()


def get_email_provider():
    print("Select your email provider:")
    print("1. Gmail")
    print("2. Outlook/Office365")
    print("3. SendGrid")
    print("4. Amazon SES")
    print("5. Custom SMTP")
    
    choice = input("\nEnter your choice (1-5): ").strip()
    return choice


def get_gmail_config():
    print("\n📧 Gmail Configuration")
    print("-" * 40)
    print("Note: You need to use an App Password, not your regular password")
    print("Generate one at: https://myaccount.google.com/apppasswords")
    print()
    
    email = input("Gmail address: ").strip()
    password = input("App Password: ").strip()
    from_name = input("Sender name (default: MatrixLead AI): ").strip() or "MatrixLead AI"
    
    return {
        "SMTP_HOST": "smtp.gmail.com",
        "SMTP_PORT": "587",
        "SMTP_USER": email,
        "SMTP_PASSWORD": password,
        "FROM_EMAIL": email,
        "FROM_NAME": from_name
    }


def get_outlook_config():
    print("\n📧 Outlook/Office365 Configuration")
    print("-" * 40)
    
    email = input("Outlook email address: ").strip()
    password = input("Password: ").strip()
    from_name = input("Sender name (default: MatrixLead AI): ").strip() or "MatrixLead AI"
    
    return {
        "SMTP_HOST": "smtp-mail.outlook.com",
        "SMTP_PORT": "587",
        "SMTP_USER": email,
        "SMTP_PASSWORD": password,
        "FROM_EMAIL": email,
        "FROM_NAME": from_name
    }


def get_sendgrid_config():
    print("\n📧 SendGrid Configuration")
    print("-" * 40)
    
    api_key = input("SendGrid API Key: ").strip()
    from_email = input("From email address: ").strip()
    from_name = input("Sender name (default: MatrixLead AI): ").strip() or "MatrixLead AI"
    
    return {
        "SMTP_HOST": "smtp.sendgrid.net",
        "SMTP_PORT": "587",
        "SMTP_USER": "apikey",
        "SMTP_PASSWORD": api_key,
        "FROM_EMAIL": from_email,
        "FROM_NAME": from_name
    }


def get_ses_config():
    print("\n📧 Amazon SES Configuration")
    print("-" * 40)
    
    region = input("AWS Region (e.g., us-east-1): ").strip()
    smtp_user = input("SMTP Username: ").strip()
    smtp_password = input("SMTP Password: ").strip()
    from_email = input("From email address: ").strip()
    from_name = input("Sender name (default: MatrixLead AI): ").strip() or "MatrixLead AI"
    
    return {
        "SMTP_HOST": f"email-smtp.{region}.amazonaws.com",
        "SMTP_PORT": "587",
        "SMTP_USER": smtp_user,
        "SMTP_PASSWORD": smtp_password,
        "FROM_EMAIL": from_email,
        "FROM_NAME": from_name
    }


def get_custom_config():
    print("\n📧 Custom SMTP Configuration")
    print("-" * 40)
    
    host = input("SMTP Host: ").strip()
    port = input("SMTP Port (default: 587): ").strip() or "587"
    user = input("SMTP Username: ").strip()
    password = input("SMTP Password: ").strip()
    from_email = input("From email address: ").strip()
    from_name = input("Sender name (default: MatrixLead AI): ").strip() or "MatrixLead AI"
    
    return {
        "SMTP_HOST": host,
        "SMTP_PORT": port,
        "SMTP_USER": user,
        "SMTP_PASSWORD": password,
        "FROM_EMAIL": from_email,
        "FROM_NAME": from_name
    }


def write_env_file(config, env_path):
    """Write configuration to .env file"""
    
    env_content = f"""# Email Configuration for MatrixLead AI
# Auto-generated by setup_email.py

# SMTP Server Settings
SMTP_HOST={config['SMTP_HOST']}
SMTP_PORT={config['SMTP_PORT']}

# Email Credentials
SMTP_USER={config['SMTP_USER']}
SMTP_PASSWORD={config['SMTP_PASSWORD']}

# Sender Information
FROM_EMAIL={config['FROM_EMAIL']}
FROM_NAME={config['FROM_NAME']}
"""
    
    with open(env_path, 'w') as f:
        f.write(env_content)
    
    print(f"\n✅ Configuration saved to: {env_path}")


def test_email_config(config):
    """Test the email configuration"""
    print("\n🧪 Testing email configuration...")
    
    try:
        import smtplib
        
        server = smtplib.SMTP(config['SMTP_HOST'], int(config['SMTP_PORT']))
        server.starttls()
        server.login(config['SMTP_USER'], config['SMTP_PASSWORD'])
        server.quit()
        
        print("✅ Email configuration is valid!")
        return True
    except Exception as e:
        print(f"❌ Configuration test failed: {e}")
        return False


def main():
    print_header()
    
    # Determine the agents directory
    script_dir = Path(__file__).parent
    agents_dir = script_dir / "agents"
    env_path = agents_dir / ".env"
    
    if not agents_dir.exists():
        print(f"❌ Error: agents directory not found at {agents_dir}")
        sys.exit(1)
    
    # Check if .env already exists
    if env_path.exists():
        overwrite = input(f"\n⚠️  {env_path} already exists. Overwrite? (y/N): ").strip().lower()
        if overwrite != 'y':
            print("Cancelled.")
            sys.exit(0)
    
    # Get provider choice
    choice = get_email_provider()
    
    # Get configuration based on choice
    config = None
    if choice == '1':
        config = get_gmail_config()
    elif choice == '2':
        config = get_outlook_config()
    elif choice == '3':
        config = get_sendgrid_config()
    elif choice == '4':
        config = get_ses_config()
    elif choice == '5':
        config = get_custom_config()
    else:
        print("❌ Invalid choice")
        sys.exit(1)
    
    # Write configuration
    write_env_file(config, env_path)
    
    # Test configuration
    test = input("\nTest email configuration now? (Y/n): ").strip().lower()
    if test != 'n':
        test_email_config(config)
    
    print("\n" + "=" * 60)
    print("Setup complete! You can now use the email service.")
    print("=" * 60)
    print("\nNext steps:")
    print("1. Restart the agents service: docker-compose restart agents")
    print("2. Test with: python test_flow.py")
    print()


if __name__ == "__main__":
    try:
        main()
    except KeyboardInterrupt:
        print("\n\nCancelled by user.")
        sys.exit(0)
